# .scrutinizer.yml
filter:
    excluded_paths:
        - tests/*

checks:
    php:
        code_rating: true

tools:
    external_code_coverage:
        timeout: 1800
        runs: 3
    php_code_coverage: false
